{% set version = "2.16.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-keras
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/keras_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/keras/keras_{{ version }}.tar.gz
  sha256: 4a03130d045b11d1bf250ba8fc88f9bbdc502137d110bd497d417010fb4db803

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-ellipsis
    - r-generics >=0.0.1
    - r-glue
    - r-magrittr
    - r-reticulate >1.22
    - r-rlang
    - r-tensorflow >2.7.0
    - r-tfruns >=1.0
    - r-zeallot
  run:
    - r-base
    - r-r6
    - r-ellipsis
    - r-generics >=0.0.1
    - r-glue
    - r-magrittr
    - r-reticulate >1.22
    - r-rlang
    - r-tensorflow >2.7.0
    - r-tfruns >=1.0
    - r-zeallot

test:
  commands:
    - $R -e "library('keras')"           # [not win]
    - "\"%R%\" -e \"library('keras')\""  # [win]

about:
  home: https://keras.rstudio.com
  license: MIT
  summary: Interface to 'Keras' <https://keras.io>, a high-level neural networks 'API'. 'Keras' was developed with a focus on enabling fast experimentation, supports both convolution based networks and recurrent networks (as well as combinations of the two), and runs seamlessly on both 'CPU' and 'GPU' devices.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - zamorarr

# Package: keras
# Type: Package
# Title: R Interface to 'Keras'
# Version: 2.2.5.0
# Authors@R: c( person("Daniel", "Falbel", role = c("ctb", "cph", "cre"), email = "daniel@rstudio.com"), person("JJ", "Allaire", role = c("aut", "cph")), person("Francois", "Chollet", role = c("aut", "cph")), person(family = "RStudio", role = c("ctb", "cph", "fnd")), person(family = "Google", role = c("ctb", "cph", "fnd")), person("Yuan", "Tang", role = c("ctb", "cph"), email = "terrytangyuan@gmail.com", comment = c(ORCID = "0000-0001-5243-233X")), person("Wouter", "Van Der Bijl", role = c("ctb", "cph")), person("Martin", "Studer", role = c("ctb", "cph")), person("Sigrid", "Keydana", role = c("ctb")) )
# Description: Interface to 'Keras' <https://keras.io>, a high-level neural networks 'API'. 'Keras' was developed with a focus on enabling fast experimentation, supports both convolution based networks and recurrent networks (as well as combinations of the two), and runs seamlessly on both 'CPU' and 'GPU' devices.
# Encoding: UTF-8
# License: MIT + file LICENSE
# URL: https://keras.rstudio.com
# BugReports: https://github.com/rstudio/keras/issues
# Depends: R (>= 3.2)
# Imports: generics (>= 0.0.1), reticulate (>= 1.10), tensorflow (>= 2.0.0), tfruns (>= 1.0), magrittr, zeallot, methods, R6
# Suggests: ggplot2, testthat (>= 2.1.0), knitr, rmarkdown, tfdatasets, jpeg
# SystemRequirements: Keras >= 2.0 (https://keras.io)
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-10-08 17:30:39 UTC; dfalbel
# Author: Daniel Falbel [ctb, cph, cre], JJ Allaire [aut, cph], Francois Chollet [aut, cph], RStudio [ctb, cph, fnd], Google [ctb, cph, fnd], Yuan Tang [ctb, cph] (<https://orcid.org/0000-0001-5243-233X>), Wouter Van Der Bijl [ctb, cph], Martin Studer [ctb, cph], Sigrid Keydana [ctb]
# Maintainer: Daniel Falbel <daniel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-10-08 18:10:02 UTC
