travis:
  secure:
    BINSTAR_TOKEN: UxuDUDeL9Kev8bxlQXkaoyrB1zvRI3ThMdD+pWFlq7uM1fIQB/WdIVMLqinrdQNeT3YrqtA01gwonmmIPJ9CDWVS/dr9QzVy8gsBgBE/vUMqPBdKayM0LGSNXRwW0e/0pq6Epdzu9rWAL1636Q2S5W2zLR5jWoTPFhSGEkyuSpLi7vMUMmbRil8bUVPCEHOcLUgLZ38AdTOzxyBoAvSL34gkeKhNtWAh2Lu7hDdYDS8FjJFGj4T07wIZAqreNkEUjQTTRbdEz9Z3oWa5/2Skjx7aHnBBT9yF8H3wYGm42M72CPM2ZANNO5dcpW7wiI/i8g+zinO90OJ2s/sxG/09G77GCvQsdJ0PKlZI3F/VdbnMjJAoBNHUrMjw+sQ0fO6WrOIlJOoqlWv0smVyq5J5PXLRtpQm4BHN9h/IFWtU4/etEs20wXTkxmlirqBV/eNCc2dFvzzb+bhobL50beLtNMLAnwZjRapuwzkNnuP+nuhk7GaMRlaeFG+0vmbzj0/PQblmAcqgbcE2Eqom3m/r7qunxW+NUfhgLI3m0llyHMBo21bgNMxyR1nHcVb/SrK7YoKZpUENuC5YRlooRD2VtHtUSYsxpFcaTOuygzvNNbIpvG3xyzPnADhJ0yKPFBc432XtxPN0bFYhq+X/8xdW4/Ukw6V7MfU6SNxWMmUuYqI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
